name: Build and Test

on: 
  workflow_dispatch:
  push:
    branches:
     - "main"
    paths:
      - "src/Transmitly.Microsoft.AspnetCore.Mvc/**"
jobs:
  build_test_deploy_channel_provider:
    uses: transmitly/transmitly/.github/workflows/build-and-deploy-channel-provider.yml@main
    with: 
      channelProviderName: Transmitly.Microsoft.AspnetCore.Mvc
    secrets: inherit
      
